name: Application Deployment
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello! The pipeline is working."
