name: Smart TV App Deployment
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  validate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello! The pipeline is working."
